### ISSUE TITLE
[Small bug, I think, in the cave for Dusk's final battle] Mathyus shoots at Demolisher early

### ISSUE THREAD

**Issue by rubyFeedback** [evancauteren/bg2-autumns-twilight-mod#10]
The old bug where the player could attack early during the cave with Dusk's final battle against the enemy mages, where we could snipe off individual mages before the end fight started, was fixed; or
at the least I could not attack early on (I could have perhaps tried once, not sure - the different
scenes were moving quite rapidly, though, so I am not sure if I could have managed. See
below for an explanation of my thought process.)

Before the final battle starts, e. g. before the enemy summons come in for Death etc..., 
Mathyus already shoots at Demolisher and wounds him. The wounds are slight, but
still I think it is equally unfair that the enemy team can attack early but the heroes party
can not. Both should start at the same time.

I am not sure why Mathyus begins to attack early. Perhaps because he has a longbow?
Either way, I think perhaps this could also be where I may interrupt Mathyus, e. g.
via some hold-in-place spell like Bigby's fist or the carnivous plant from one of
Lava's mod. But I think the proper way to fix this is to delay Mathyus attack somehow.
I think he attacks Demolisher because the battle has technically begun, and the dog
is simply closest to Mathyus. Perhaps the delay could be offset a little, e. g. after the
summon; at the least for Mathyus, since he seems to be the only one with a ranged
weapon on the enemy team.

**Comment by RamosPabloA** [comment]
Done. I put a little timer of a couple of seconds! It will be in the next update
