### ISSUE TITLE
Vidomina appears with a delay - not sure if this qualifies as a bug though

### ISSUE THREAD

**Issue by rubyFeedback** [evancauteren/bg2-autumns-twilight-mod#12]
I just entered the area where Vidomina is. Initially she was not there, though, then she
appeared after like 2 seconds of entering there.

I clicked on her to speak with her. Now the speech is finished ... and an intro by Vidomina is
suddenly triggered, aka "Greetings". I believe that intro should first spawn, perhaps right
when Vidomina is showing up - instantly. With the current delay, we can interact with her,
and then she does her "Greetings" intro, but we just spoke to her, so this makes no sense.

This is probably not a bug as such, mostly just a cosmetics thing.

(By the way, it may be simpler to spawn all the NPCs the moment we arrive in the area. Not sure why there is a delay, the delay is a bit confusing. I could swear there was also a delay when the death knight spawned before, but I am not certain. I first moved to the death knight actually, then suddenly Vidomina spawned, I clicked on her and spoke to her; and after speaking with her, the "Greetings" intro was done. The intro should come probably upon seeing Vidomina. The map could perhaps have a bit more of a long corridor before reaching those NPCs, that may help a bit indirectly.)

**Comment by RamosPabloA** [comment]
The Vidomina model, being "new", takes a couple of seconds to load. This happens the first time it appears and usually occurs when you start the game and enter this area for the first time. I don’t remember exactly, but I believe if you enter the area for the first time (a second time), it should load immediately.

**Comment by RamosPabloA** [comment]
I’ve added a 3-second timer to allow time for Vidomina’s creation, as well as some slight modifications to speed up the process. Ideally, she should be created within 1 second, so by the time the player approaches the center of the area, she’ll already be there.
