### ISSUE TITLE
Chonuja is invincible

### ISSUE THREAD

**Issue by rubyFeedback** [evancauteren/bg2-autumns-twilight-mod#15]
So I just fought Chonuja and he triggers his speech where he will escape.

He is, however had, slowed and under effects of horror as well as the carnivorous plant slowing him down further.

So he just stays in the remain, can not be killed, and does not leave either.

Not sure if that was intended or not, but I think after the speech he gives, he should go away. Right now he appears to move away but due to slow, does not seem to make it, then "forgets" about moving away altogether.

**Comment by RamosPabloA** [comment]
Depending on the area, he should leave. If he stays, it’s a bug because his flee script was interrupted. I’ll add a patch to prevent that from happening.
