### ISSUE TITLE
[Small bug, I think] Chonuja's stone can not be removed

### ISSUE THREAD

**Issue by rubyFeedback** [evancauteren/bg2-autumns-twilight-mod#16]
I recently obtained chonuja's stone. I now have three wardstones.

The first two can be relocated into a bag of holding. The chonuja stone can not
be moved at all and is now at a fixed place in the inventory, which is a bit
inconvenient as I don't have much space left in the inventory. That's why I
normally move stuff into a container.

The strange thing is that the two stones before that, can be moved into a bag
without problem. I believe the third stone, chonuja, should also be relocatable
into a bag - not sure why it is not. (Perhaps it has to do with the prior bug of
chonjua not moving away while remaining at minimum hp, and unkillable.)

**Comment by RamosPabloA** [comment]
The item should be movable in the inventory—at least that's what I’m seeing in the item’s code. If it can’t be moved, don’t worry, it’s only temporary, as the quest itself will soon take care of allowing it to be moved.
