### ISSUE TITLE
[Suggestion for Dusk] Dusk is somewhat vulnerable to poison.

### ISSUE THREAD

**Issue by rubyFeedback** [evancauteren/bg2-autumns-twilight-mod#17]
So in the last three big fights or so, I had the problem that Dusk was constantly poisoned.

Other members in the party, such as Korgan, can work around this issue by e. g. wearing
the ring that grants immunity to poison, or the amulet, or other things, but Dusk can not
use any of these items.

There are workarounds, of course, such as letting only those characters take hits who can
deal with poison, so it is not a real issue per se. Plus, Dusk is already very powerful in its
own right, with his defaults as well as special gear, so I am not necessarily suggesting to
make Dusk himself stronger.

But, I was wondering ... what if we could have an option of upgrading a weapon or armour
that would yield poison resistance? Perhaps not total immunity but reduced damage from
poison effects? Or perhaps immunity for a certain duration such as three rounds or anything
that makes sense.

To not just boost Dusk even further, without any downside, perhaps this anti-poison use of an
item could be in exchange of something else, e. g. where Dusk can specialize a little bit via 
anti-poison, but would lose, in one of those items, a little bit. I am not sure which item ...
perhaps the one that grants some resistances elsewhere? Or an item that modifies a stat,
to reduce the boost of that stat while granting that anti-immunity thing. This could be done
via Mathyus, or perhaps by one of the NPC merchants in the hideout, just as they offer a 
slight upgrade to boots of speed, against a high fee.

In the last two fights I kept on losing Dusk due to poison and had to ress him. I could have
replayed it again, and probably kept Dusk alive, but that would have taken longer, so I decided
to just ress him instead by Viconia. Dusk was already in backrow and drinking healing potions
but the poison did too much damage before Viconia got in her full heal, so perhaps we just need
a short duration anti-poison effect, at the cost of lowering another benefit. Anyway, just a suggestion.

**Comment by RamosPabloA** [comment]
In the next update, Tamika will sell Venomguard, a +2 shield that grants immunity to poison.
