### ISSUE TITLE
[Possibly a tiny bug or a minor issue] Dusk has two staffs/spears?

### ISSUE THREAD

**Issue by rubyFeedback** [evancauteren/bg2-autumns-twilight-mod#6]
I am doing a new test-run with the newly released mod here. I'll give more feedback lateron, in particular about Fall. But I ran into a strange thing with Dusk just now.

So Dusk now has ... two staffs. First, the melee-centric close variant which is also known from the older mod. This is the staff that can lateron dispel. A two-handed weapon.

But we also now seem to get a new spear-staff? One that can be wielded in one hand, and also be thrown. So this adds versatility.

However had, both have the word "shilmastan" or whatever it is. Which makes me wonder ... they are two objects. But aren't they the same staff? Or does Dusk now have two staffs?

It's a bit confusing to me; from the description it almost seems as if it should be a single item and we can decide which variant to use. But clearly Dusk has two items in inventory, which is a bit weird to me.

Actually I prefer Dusk wielding two bastard swords, so I almost never use the staff unless I need its dispel ability. But now I see to have two different staffs, which confuses me. If it is a bug or a minor issue then it could perhaps be addressed, but IF it is not a bug then perhaps the dialogue options can be made more clear about it, in particular since I don't need it (but it is nice that it can be thrown, that adds option for Dusk e. g. if he is too injured he can retreat to the backrow and still throw the staff to do damage).

Or perhaps it is another weapon - perhaps the name could then be changed a bit, so as to not confuse it with the staff. (In older gameplays I also managed to clone one of the two bastardswords; I haven't managed to do so again, but if I run into it I'll make sure to report it again.)

**Comment by RamosPabloA** [comment]
It's a bug. You should only have 1 of the 2 staves. Something must have happened with the inventory during the conversation. The thing is, the old staff should have been removed and the new spear-staff left. I've already put out a patch to prevent that from happening. Thanks for reporting it.

**Comment by RamosPabloA** [comment]
Fix loaded for the next release.
