### ISSUE TITLE
[Possible small bug] Longbow Blizzard

### ISSUE THREAD

**Issue by rubyFeedback** [evancauteren/bg2-autumns-twilight-mod#7]
So Fall just obtained the Longbow called Blizzard. However had, upon wielding it in the proper slot, nothing changed; the weapon did not appear to register.

I removed all other weapons and tried to equip it again - it was wielded (so it filled the correct slot just fine), but the main portrait did not change, whereas with all other weapons, the weapon will instead appear in the right or left hand (or both).

I gave it to Korgan then but same problem - the weapon did not show up upon wielding. There may be an issue with that weapon specifically; it should, like any other weapon, register in the main portrait. (Note that other weapons in the same mod, do properly show up, so I think there is something wrong specifically only with that weapon, perhaps something that invalidates some call or register functionality.)

Edit: I also looked for the weapon damage calculation part; it said "Fist", so this is not just an animation issue - the weapon really does not register at all as a weapon. The only thing that works is to wield it in a proper weapon slot, but that does appear to do nothing else.

**Comment by RamosPabloA** [comment]
Hello! I don’t quite understand the issue. For example, I can see the bow equipped in the quick weapon slot icon. The bow is visible in the archer’s hand, and the type of arrow being used is shown in the portrait. For the bow to appear on the character in the inventory, you need to have arrows in the quiver. If you have a screenshot of the issue, that might help (I tested Blizzard and a regular Longbow, and both work the same in terms of visual representation).

![imagen](https://github.com/user-attachments/assets/698b936f-2e50-4694-bb01-c5d335401be4)

**Comment by rubyFeedback** [comment]
Right - it works fine actually; I had no ammunition. I just found that out when I equipped the silver arrow from one of Lava's mods onto the one who has the bow, so there is no bug here.
